#!/usr/bin/python3
#
# this file is part of gstation-edit
# Copyright (C) F LAIGNEL 2009-2017 <fengalin@free.fr>
#
# gstation-edit is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the
# Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# gstation-edit is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program.  If not, see <http://www.gnu.org/licenses/>.

import traceback

import gi
gi.require_version('Gtk', '3.0')
from gi.repository import Gtk

try:
    from gstation_edit.app import GStationEdit
except Exception as exc:
    print('==> Failed to start GStation-Edit. Did you install py_alsa?')
    print(traceback.format_exc())

if __name__ == '__main__':
  gstation_edit = GStationEdit()
  Gtk.main()
