#!/usr/bin/env python

import sys
import os

from distutils.core import run_setup


def capture(cmd):
    return os.popen(cmd).read().strip()

def removeall(path):
    if not os.path.isdir(path):
        return

    files=os.listdir(path)

    for x in files:
        fullpath=os.path.join(path, x)
        if os.path.isfile(fullpath):
            f = os.remove
            rmgeneric(fullpath, f)
        elif os.path.isdir(fullpath):
            removeall(fullpath)
            f = os.rmdir
            rmgeneric(fullpath, f)

def rmgeneric(path, __func__):
    try:
        __func__(path)
    except OSError, (errno, strerror):
        pass



dist = run_setup('./setup_script.py', script_args=sys.argv[1:], stop_after='commandline')

cmd = dist.get_command_obj('install')
cmd.finalize_options()

install_data_path = os.path.join(cmd.install_data, 'share')
install_scripts_path = cmd.install_scripts

config_file = file(os.path.join('gstation_edit', 'config.py'), 'wt')
config_file.write("""
# generated by setup.py
DATA_ROOT_DIR = "%s"
"""%(os.path.join(install_data_path, 'gstation-edit'))
  )
config_file.close()

run_setup('./setup_script.py', script_args=sys.argv[1:], stop_after='run')

# Finalize fix path
try:
    desktop_file_path = os.path.join(install_data_path,
                                     'applications',
                                     'gstation-edit.desktop')
    desktop_file = file(desktop_file_path, 'rt')
    lines = desktop_file.readlines()
    desktop_file.close()
    desktop_file = file(desktop_file_path, 'wt')
    for line in lines:
      line = line.replace('%scripts_path%', install_scripts_path)
      desktop_file.write(line)
    desktop_file.close()
except:
    print('Problem while fixing gstation-edit.desktop path')
  
# Cleanup remove /build, and *.pyc files:
print("Cleaning up...")
try:
    removeall("build/")
    os.rmdir("build/")
except:
    pass
try:
    for f in os.listdir("."):
        if os.path.isfile(f):
            if os.path.splitext(os.path.basename(f))[1] == ".pyc":
                os.remove(f)
except:
    pass

try:
    os.remove(os.path.join('gstation_edit', 'config.py'))
except:
    pass
